In [381]:
import pandas as pd
import numpy as np

In [382]:
df = pd.read_csv('candy.csv', encoding = 'ISO-8859-1')

In [383]:
#df.head()

In [384]:
df.set_index('Internal ID', inplace = True)

In [385]:
#df.head(2)

In [386]:
df = df.rename(columns={'Q3: AGE': 'age', 'Q1: GOING OUT?': 'going out', 'Q2: GENDER': 'gender'} )

In [387]:
#df.head(2)

In [388]:
df.age.describe()

count     2376
unique     106
top         40
freq        92
Name: age, dtype: object

In [389]:
#df.age.value_counts()

In [390]:
df.age.isnull().sum()

84

In [391]:
#df[df.age.isnull()]

In [392]:
#df[df.age.notnull()].head()

In [393]:
df['age'] = df['age'].str.replace('\D+', '  ')

In [394]:
#df.age.value_counts()

In [395]:
df.age.isnull().sum()

84

In [396]:
df['age'] = df['age'].str.replace(' ', '')

In [397]:
#df.age.value_counts()

In [398]:
df.age.isnull().sum()

84

In [399]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [400]:
df.age.dtype

dtype('float64')

In [401]:
df.age.isnull().sum()

100

In [402]:
#df.age.value_counts()

In [403]:
#df['age'] = df['age'].astype(int)

In [404]:
#df.age.dtype

In [405]:
df[df['age'] > 90]

,going out,gender,age,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers (a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
Internal ID,,,,,,,,,,,,,,,,,,,,,
90274268,No,Male,4555.0,US,NC,JOY,MEH,JOY,DESPAIR,NaN,...,Licorice in anything,Two things from my childhood in upstate NY. We...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(70, 22)"
90274337,No,Other,312.0,Canada,BC,MEH,MEH,JOY,DESPAIR,MEH,...,pillow face. rubber bats. opening a pumpkin a...,I am Groot!,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(69, 23)"
90274994,No,I'd rather not say,99.0,US,NY,MEH,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(79, 20)"
90275982,No,Male,394.0,US of A,Michigin,JOY,NaN,NaN,NaN,NaN,...,NaN,NaN,White and gold,NaN,Sunday,NaN,NaN,NaN,NaN,NaN
90276469,No,I'd rather not say,102.0,A,A,MEH,DESPAIR,JOY,DESPAIR,DESPAIR,...,A,A,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(71, 20)"
90278741,No,I'd rather not say,2450.0,USA,GA,JOY,DESPAIR,JOY,DESPAIR,MEH,...,"caramel apple sugar babies, salt water taffy, ...","Not all ""non-black licorice"" are the same!",Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(71, 30)"
90279273,No,I'd rather not say,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90279712,No,I'd rather not say,100.0,Usa,New york,MEH,DESPAIR,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(78, 23)"
90279807,Yes,I'd rather not say,1000.0,Atlantis,"Emerald City, Petrolia",MEH,JOY,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(76, 34)"
90287278,No,Male,7012.0,USA,California,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [406]:
#df['age'] = df['age'].replace((df['age'] > 100), np.nan)

In [407]:
#df[df['age'] > 100]

In [408]:
df.age.isnull().sum()

100

In [409]:
#df.age.value_counts()

In [410]:
#df['age'] = df['age'].replace([100.0 - 7012.0], np.nan)

In [411]:
#df.age.value_counts()

In [412]:
df.age.isnull().sum()

100

In [413]:
df.age.mean()

48.626694915254234

In [414]:
df.age.max()

7012.0

In [415]:
df.age.min()

1.0

In [416]:
#df.age.value_counts()

In [417]:
df['age'] = df['age'].replace(2450, np.mean((24,50)))

In [418]:
df['age'] = df['age'].replace(4555, np.mean((45,55)))

In [419]:
df['age'] = df['age'].replace(394, 39)

In [420]:
df['age'] = df['age'].replace(7012, 71)

In [421]:
df[df['age'] > 90]

,going out,gender,age,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers (a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
Internal ID,,,,,,,,,,,,,,,,,,,,,
90274337,No,Other,312.0,Canada,BC,MEH,MEH,JOY,DESPAIR,MEH,...,pillow face. rubber bats. opening a pumpkin a...,I am Groot!,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(69, 23)"
90274994,No,I'd rather not say,99.0,US,NY,MEH,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(79, 20)"
90276469,No,I'd rather not say,102.0,A,A,MEH,DESPAIR,JOY,DESPAIR,DESPAIR,...,A,A,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(71, 20)"
90279273,No,I'd rather not say,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90279712,No,I'd rather not say,100.0,Usa,New york,MEH,DESPAIR,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(78, 23)"
90279807,Yes,I'd rather not say,1000.0,Atlantis,"Emerald City, Petrolia",MEH,JOY,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(76, 34)"

In [422]:
#df.age.value_counts()

In [423]:
#df['age'].replace((df['age'] > 90), np.nan)

In [424]:
#df.age.isnull().sum()

In [425]:
mean_age = df['age'].mean(skipna=True)
mean_age

42.603813559322035

In [426]:
#df[df['age'] > 90]

In [432]:
df['age'] = df.age.mask((df['age'] > 90), mean_age)

In [433]:
df['age'] = df.age.mask((df['age'] < 5), mean_age)

In [434]:
df[df['age'] > 90]

Empty DataFrame
Columns: [going out, gender, age, Q4: COUNTRY, Q5: STATE, PROVINCE, COUNTY, ETC, Q6 | 100 Grand Bar, Q6 | Anonymous brown globs that come in black and orange wrappers	(a.k.a. Mary Janes), Q6 | Any full-sized candy bar, Q6 | Black Jacks, Q6 | Bonkers (the candy), Q6 | Bonkers (the board game), Q6 | Bottle Caps, Q6 | Box'o'Raisins, Q6 | Broken glow stick, Q6 | Butterfinger, Q6 | Cadbury Creme Eggs, Q6 | Candy Corn, Q6 | Candy that is clearly just the stuff given out for free at restaurants, Q6 | Caramellos, Q6 | Cash, or other forms of legal tender, Q6 | Chardonnay, Q6 | Chick-o-Sticks (we donÕt know what that is), Q6 | Chiclets, Q6 | Coffee Crisp, Q6 | Creepy Religious comics/Chick Tracts, Q6 | Dental paraphenalia, Q6 | Dots, Q6 | Dove Bars, Q6 | Fuzzy Peaches, Q6 | Generic Brand Acetaminophen, Q6 | Glow sticks, Q6 | Goo Goo Clusters, Q6 | Good N' Plenty, Q6 | Gum from baseball cards, Q6 | Gummy Bears straight up, Q6 | Hard Candy, Q6 | Healthy Fruit, Q6 | Heath Bar, Q6 | Hershey's Dark Chocolate, Q6 | HersheyÕs Milk Chocolate, Q6 | Hershey's Kisses, Q6 | Hugs (actual physical hugs), Q6 | Jolly Rancher (bad flavor), Q6 | Jolly Ranchers (good flavor), Q6 | JoyJoy (Mit Iodine!), Q6 | Junior Mints, Q6 | Senior Mints, Q6 | Kale smoothie, Q6 | Kinder Happy Hippo, Q6 | Kit Kat, Q6 | LaffyTaffy, Q6 | LemonHeads, Q6 | Licorice (not black), Q6 | Licorice (yes black), Q6 | Lindt Truffle, Q6 | Lollipops, Q6 | Mars, Q6 | Maynards, Q6 | Mike and Ike, Q6 | Milk Duds, Q6 | Milky Way, Q6 | Regular M&Ms, Q6 | Peanut M&MÕs, Q6 | Blue M&M's, Q6 | Red M&M's, Q6 | Green Party M&M's, Q6 | Independent M&M's, Q6 | Abstained from M&M'ing., Q6 | Minibags of chips, Q6 | Mint Kisses, Q6 | Mint Juleps, Q6 | Mr. Goodbar, Q6 | Necco Wafers, Q6 | Nerds, Q6 | Nestle Crunch, Q6 | Now'n'Laters, Q6 | Peeps, Q6 | Pencils, Q6 | Pixy Stix, Q6 | Real Housewives of Orange County Season 9 Blue-Ray, Q6 | ReeseÕs Peanut Butter Cups, Q6 | Reese's Pieces, Q6 | Reggie Jackson Bar, Q6 | Rolos, Q6 | Sandwich-sized bags filled with BooBerry Crunch, Q6 | Skittles, Q6 | Smarties (American), Q6 | Smarties (Commonwealth), Q6 | Snickers, Q6 | Sourpatch Kids (i.e. abominations of nature), Q6 | Spotted Dick, Q6 | Starburst, Q6 | Sweet Tarts, Q6 | Swedish Fish, Q6 | Sweetums (a friend to diabetes), Q6 | Take 5, Q6 | Tic Tacs, Q6 | Those odd marshmallow circus peanut things, Q6 | Three Musketeers, Q6 | Tolberone something or other, ...]
Index: []

[0 rows x 119 columns]

In [435]:
df[df['age'] < 5]

Empty DataFrame
Columns: [going out, gender, age, Q4: COUNTRY, Q5: STATE, PROVINCE, COUNTY, ETC, Q6 | 100 Grand Bar, Q6 | Anonymous brown globs that come in black and orange wrappers	(a.k.a. Mary Janes), Q6 | Any full-sized candy bar, Q6 | Black Jacks, Q6 | Bonkers (the candy), Q6 | Bonkers (the board game), Q6 | Bottle Caps, Q6 | Box'o'Raisins, Q6 | Broken glow stick, Q6 | Butterfinger, Q6 | Cadbury Creme Eggs, Q6 | Candy Corn, Q6 | Candy that is clearly just the stuff given out for free at restaurants, Q6 | Caramellos, Q6 | Cash, or other forms of legal tender, Q6 | Chardonnay, Q6 | Chick-o-Sticks (we donÕt know what that is), Q6 | Chiclets, Q6 | Coffee Crisp, Q6 | Creepy Religious comics/Chick Tracts, Q6 | Dental paraphenalia, Q6 | Dots, Q6 | Dove Bars, Q6 | Fuzzy Peaches, Q6 | Generic Brand Acetaminophen, Q6 | Glow sticks, Q6 | Goo Goo Clusters, Q6 | Good N' Plenty, Q6 | Gum from baseball cards, Q6 | Gummy Bears straight up, Q6 | Hard Candy, Q6 | Healthy Fruit, Q6 | Heath Bar, Q6 | Hershey's Dark Chocolate, Q6 | HersheyÕs Milk Chocolate, Q6 | Hershey's Kisses, Q6 | Hugs (actual physical hugs), Q6 | Jolly Rancher (bad flavor), Q6 | Jolly Ranchers (good flavor), Q6 | JoyJoy (Mit Iodine!), Q6 | Junior Mints, Q6 | Senior Mints, Q6 | Kale smoothie, Q6 | Kinder Happy Hippo, Q6 | Kit Kat, Q6 | LaffyTaffy, Q6 | LemonHeads, Q6 | Licorice (not black), Q6 | Licorice (yes black), Q6 | Lindt Truffle, Q6 | Lollipops, Q6 | Mars, Q6 | Maynards, Q6 | Mike and Ike, Q6 | Milk Duds, Q6 | Milky Way, Q6 | Regular M&Ms, Q6 | Peanut M&MÕs, Q6 | Blue M&M's, Q6 | Red M&M's, Q6 | Green Party M&M's, Q6 | Independent M&M's, Q6 | Abstained from M&M'ing., Q6 | Minibags of chips, Q6 | Mint Kisses, Q6 | Mint Juleps, Q6 | Mr. Goodbar, Q6 | Necco Wafers, Q6 | Nerds, Q6 | Nestle Crunch, Q6 | Now'n'Laters, Q6 | Peeps, Q6 | Pencils, Q6 | Pixy Stix, Q6 | Real Housewives of Orange County Season 9 Blue-Ray, Q6 | ReeseÕs Peanut Butter Cups, Q6 | Reese's Pieces, Q6 | Reggie Jackson Bar, Q6 | Rolos, Q6 | Sandwich-sized bags filled with BooBerry Crunch, Q6 | Skittles, Q6 | Smarties (American), Q6 | Smarties (Commonwealth), Q6 | Snickers, Q6 | Sourpatch Kids (i.e. abominations of nature), Q6 | Spotted Dick, Q6 | Starburst, Q6 | Sweet Tarts, Q6 | Swedish Fish, Q6 | Sweetums (a friend to diabetes), Q6 | Take 5, Q6 | Tic Tacs, Q6 | Those odd marshmallow circus peanut things, Q6 | Three Musketeers, Q6 | Tolberone something or other, ...]
Index: []

[0 rows x 119 columns]

In [436]:
#df.age.value_counts()

In [437]:
df.age.max()

90.0

In [438]:
df.age.min()

5.0

In [439]:
df[df['age'] < 10]

,going out,gender,age,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers (a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
Internal ID,,,,,,,,,,,,,,,,,,,,,
90273811,Yes,Female,9.0,usa,va,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90273934,Yes,Female,6.0,United States,Colorado,MEH,DESPAIR,JOY,DESPAIR,JOY,...,crunchy frog,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(64, 18)"
90275243,Yes,Female,7.0,Australia,Sydney,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90275672,Yes,Male,9.0,'merica,Merlin,JOY,DESPAIR,JOY,MEH,MEH,...,Twizzlers. Dramamine.,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(71, 32)"
90276709,Yes,Male,8.0,United States,Oregon,MEH,DESPAIR,JOY,NaN,NaN,...,Drug's,NaN,Blue and black,NaN,Friday,1.0,NaN,NaN,NaN,"(37, 17)"
90277137,Yes,Male,9.0,Canada,British Columbia,JOY,MEH,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,NaN,NaN,NaN,NaN
90277406,No,Female,5.0,USA,CA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90278444,Yes,Female,8.0,USA,TX,NaN,MEH,JOY,NaN,NaN,...,Any minty chocolate,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(58, 6)"
90278873,Yes,Male,7.0,CANADA,ONTARIO,NaN,MEH,MEH,NaN,JOY,...,Loose peanuts in shell,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(74, 11)"
90279571,No,Male,9.0,USA,Kentucky,MEH,JOY,JOY,DESPAIR,JOY,...,Toothbrush,NaN,White and gold,NaN,Sunday,NaN,NaN,NaN,NaN,NaN
90279648,Yes,Male,6.0,USA,California,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [440]:
#df.age.value_counts()

In [441]:
mean_age1 = df['age'].mean(skipna=True)
mean_age1

42.03747217035335

In [442]:
df.age.nunique()

76

In [443]:
df.age.unique()

array([        nan, 44.        , 49.        , 40.        , 23.        ,
       53.        , 33.        , 43.        , 56.        , 64.        ,
       37.        , 59.        , 48.        , 54.        , 36.        ,
       45.        , 25.        , 34.        , 35.        , 38.        ,
       58.        , 50.        , 47.        , 16.        , 52.        ,
       63.        , 65.        , 41.        , 27.        , 31.        ,
       61.        , 46.        , 42.        , 62.        , 29.        ,
       39.        , 32.        , 28.        , 69.        , 67.        ,
       30.        , 22.        , 26.        , 51.        , 70.        ,
       24.        , 18.        , 19.        , 57.        , 60.        ,
       66.        , 12.        , 55.        , 72.        , 21.        ,
       11.        ,  9.        , 68.        , 20.        ,  6.        ,
       10.        , 71.        , 90.        , 13.        , 42.60381356,
        7.        , 88.        , 74.        , 17.        , 15.        ,
        8.        , 75.        ,  5.        , 14.        , 76.        ,
       77.        , 73.        ])

In [444]:
df.age.isnull().sum()

100

In [445]:
df['age'].fillna(value = mean_age1, inplace = True)

In [446]:
df.age.isnull().sum()

0

In [447]:
df.age.dtype

dtype('float64')

In [448]:
df['age'] = df['age'].round(0).astype(int)

In [449]:
df.age.dtype

dtype('int64')

In [450]:
df.age.value_counts()

42    179
43     95
40     92
37     90
34     90
36     79
35     77
38     76
44     76
45     75
33     75
41     74
50     73
39     70
49     69
32     68
48     64
47     63
30     62
53     57
46     56
52     50
56     46
31     45
27     45
51     41
28     37
54     36
58     34
60     32
     ...
18     10
66      9
12      9
23      9
68      8
15      8
70      8
71      7
11      7
72      6
67      6
13      6
69      5
17      5
9       4
16      4
73      4
75      3
10      3
19      3
14      2
8       2
90      2
6       2
76      2
7       2
74      1
88      1
5       1
77      1
Name: age, Length: 75, dtype: int64

In [452]:
df

,going out,gender,age,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers (a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
Internal ID,,,,,,,,,,,,,,,,,,,,,
90258773,NaN,NaN,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
90272852,No,Male,42,NaN,NaN,JOY,DESPAIR,JOY,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"(75, 23)"
90272853,No,Male,53,usa,Colorado,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(55, 5)"
90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,MEH,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(76, 24)"
90272859,No,Female,53,Us,Wa,MEH,DESPAIR,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(70, 28)"
90272861,Yes,Male,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272865,No,Male,56,Canada,Quebec,JOY,MEH,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(73, 24)"
90272866,No,Male,64,US,NY,MEH,MEH,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(77, 24)"
90272867,Yes,Male,43,Murica,California,JOY,DESPAIR,JOY,MEH,MEH,...,Rain on halloween and nuclear war. I thought w...,Anything hershey should automatically get rank...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,NaN
90272868,No,Female,37,Canada,Ontario,MEH,JOY,JOY,MEH,JOY,...,Coupons,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 25)"
90272878,No,Male,64,USA,Texas,JOY,MEH,JOY,MEH,JOY,...,NaN,NaN,NaN,NaN,Friday,NaN,1.0,NaN,NaN,"(74, 30)"
90272880,No,I'd rather not say,59,USA,NEW YORK,JOY,MEH,JOY,JOY,MEH,...,fake licorice,Happy Halloween,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(79, 5)"
90272881,No,Male,48,US,CO,MEH,DESPAIR,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(79, 29)"
90272883,No,Female,54,United States,IN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272884,No,Female,36,United States,MN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272885,No,Male,45,uk,aberdeenshire,NaN,MEH,JOY,MEH,NaN,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(58, 5)"
90272886,Yes,Male,33,Canada,Alberta,MEH,DESPAIR,JOY,MEH,JOY,...,A muffin,Trick or treating isn't complete until you fin...,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(76, 13)"
90272887,Yes,Male,37,United States,"Wisconsin, 53705",MEH,DESPAIR,JOY,NaN,NaN,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(85, 16)"
90272891,No,Female,49,United States,RI,JOY,MEH,JOY,DESPAIR,DESPAIR,...,NaN,Suggest all households adopt my tradition of c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272892,No,Male,48,United States,NC,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272894,No,Male,25,United Kingdom,Scotland,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272895,No,Male,34,united states,minnesota,MEH,DESPAIR,JOY,NaN,NaN,...,stern comments about the evils of the holiday ...,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(80, 25)"
90272897,No,Male,35,USA,Michigan,JOY,DESPAIR,JOY,DESPAIR,MEH,...,Russell Stover,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(69, 22)"
90272898,Yes,Male,38,United States,Florida,NaN,DESPAIR,JOY,NaN,MEH,...,Popcorn,One house in our neighborhood was just handing...,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(74, 26)"
90272899,No,Male,58,USA,New Jersey,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(73, 25)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90308441,No,Male,46,Canada,Alberta,JOY,DESPAIR,JOY,MEH,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(76, 27)"
90309452,NaN,NaN,42,NaN,NaN,JOY,DESPAIR,JOY,DESPAIR,NaN,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(76, 10)"
90309529,Yes,Male,52,United States,Pennsylvania,MEH,MEH,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 19)"
90309907,Yes,Female,68,Usa,Washington,JOY,JOY,JOY,DESPAIR,MEH,...,Tums,"No fresh fruir, please",NaN,NaN,NaN,1.0,NaN,NaN,NaN,"(21, 5)"
90310127,No,Male,39,US,NH,JOY,MEH,JOY,NaN,NaN,...,jelly beans,NaN,Blue and black,NaN,Friday,NaN,NaN,NaN,1.0,"(68, 56)"
90310353,No,Female,52,usa,ny,MEH,DESPAIR,JOY,MEH,JOY,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(60, 21)"
90310689,No,Female,57,USA,California,JOY,DESPAIR,JOY,MEH,DESPAIR,...,Those flying saucer candies that taste like th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90310734,No,Male,25,USA,KY,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90311056,No,Male,48,usa,Connecticut,JOY,DESPAIR,JOY,NaN,NaN,...,NaN,NaN,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(71, 26)"
90311726,No,Female,27,usa,North Carolina,JOY,DESPAIR,JOY,MEH,MEH,...,"Bandaids, fruit leather",NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(67, 13)"
90312734,NaN,NaN,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90312849,No,Male,42,usa,dc,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(74, 17)"
90313039,No,Female,26,USA,Washington State,MEH,DESPAIR,JOY,NaN,NaN,...,NaN,"If you can't beat em, sweetums! Diabetes! Figh...",White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(74, 21)"
90313049,No,Female,39,United States,New York,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,I saw someone post an image on facebook last m...,Blue and black,NaN,Sunday,NaN,1.0,NaN,NaN,"(63, 22)"
90313164,No,Female,34,Canada,British Columbia,NaN,JOY,JOY,NaN,NaN,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(74, 20)"
90313211,No,Female,34,Canada,Nova Scotia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90313279,NaN,Female,67,USA,Missouri,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90313286,No,Female,27,United States,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90313345,No,Female,43,USA,PA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90313367,No,Female,60,usa,Massachusetts,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90313850,No,NaN,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90313861,No,Other,25,USA,Washington,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90313947,No,Female,43,Canada,BC,JOY,DESPAIR,JOY,DESPAIR,MEH,...,what was that gum that smelled like aftershave...,thanks for the survey!,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(62, 4)"
90313974,No,Female,40,canada,bc,MEH,DESPAIR,JOY,DESPAIR,MEH,...,Maltesers,NaN,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(68, 29)"
90314022,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,MEH,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(68, 39)"
90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,Capers,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [454]:
df['going out'].describe()

count     2350
unique       2
top         No
freq      2038
Name: going out, dtype: object

In [455]:
df['going out'].unique()

array([nan, 'No', 'Yes'], dtype=object)

In [458]:
df['going out'].isnull().sum()

110

In [456]:
df['gender'].describe()

count     2419
unique       4
top       Male
freq      1467
Name: gender, dtype: object

In [457]:
df['gender'].unique()

array([nan, 'Male', 'Female', "I'd rather not say", 'Other'], dtype=object)

In [459]:
df['gender'].isnull().sum()

41

In [463]:
df.shape

(2460, 119)

In [469]:
multiple_null = df.dropna(thresh=20)
multiple_null.shape

(1797, 119)